/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buscaminaspoo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class Juego extends javax.swing.JFrame {
    int Num_Filas = 10;
    int Num_Columnas = 10;
    int Num_Minas = 20;
    JButton [][] BotonesTablero;
    TableroBuscaminas tablerobuscaminas;

    /**
     * Creates new form Juego
     */
    public Juego() 
    {
        initComponents();
        CargarControles();
        CrearTablero();
    }
    
    private void CrearTablero() 
    {
        tablerobuscaminas = new TableroBuscaminas(Num_Filas, Num_Columnas, Num_Minas);
        tablerobuscaminas.setPartidaPerdida(new Consumer<List<Casilla>>() 
        {
            @Override
            public void accept(List<Casilla> t) {
                for( Casilla Casilla_Mina: t){
                    BotonesTablero[Casilla_Mina.getFila()][ Casilla_Mina.getColumna()].setText("*");
                }
            }
        });

        tablerobuscaminas.setCasilla_Abierta(new Consumer<Casilla>(){
            @Override
            public void accept(Casilla t){
                 BotonesTablero[t.getFila()][ t.getColumna()].setEnabled(false);
                 BotonesTablero[t.getFila()][t.getColumna()].setText(t.getNum_Mina_Alrededor() == 0?"": t.getNum_Mina_Alrededor()+"");

            }
        });
        tablerobuscaminas.ImprimirTablero();
    }

    
    private void CargarControles(){
    int PosXreferencia = 25;
    int PosYreferencia = 25;
    int Ancho = 30;
    int Alto = 30;

    getContentPane().setLayout(null);
    BotonesTablero = new JButton[Num_Filas][Num_Columnas];

    for (int i = 0; i < BotonesTablero.length; i++) {
        for (int j = 0; j < BotonesTablero[i].length; j++) {
            BotonesTablero[i][j] = new JButton();
            BotonesTablero[i][j].setName(i + "," + j);
            int PosX = PosXreferencia + j * Ancho;
            int PosY = PosYreferencia + i * Alto;
            BotonesTablero[i][j].setBounds(PosX, PosY, Ancho, Alto);
            BotonesTablero[i][j].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnClick(e);
                }
            });
            getContentPane().add(BotonesTablero[i][j]);
        }
    }

    setSize(400, 400); // asegura que el JFrame tenga tamaño visible
}

    
    private void btnClick(ActionEvent e) 
    {
        JButton btn = (JButton)e.getSource();
        String[] coordenada = btn.getName().split(",");
        int PosFila = Integer.parseInt(coordenada[0]);
        int PosColumna = Integer.parseInt(coordenada[1]);
        JOptionPane.showMessageDialog(rootPane,PosFila + "," + PosColumna);
        tablerobuscaminas.Seleccionar_Casilla(PosFila, PosColumna);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
